services:
  web:
    build: .
    command: "/dist/main"
    ports:
      - "5000:5000"
    volumes:
      - ~/dog-pictures:/pictures
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: doggo-photos-db
      MYSQL_USER: andrew
      MYSQL_PASSWORD: password
    ports:
      - 3306
    healthcheck:
      test: ["CMD", "mysql", "ping", "andrew:apple@localhost:3303"]
      timeout: 10s
      retries: 10

volumes:
  pictures:
  db_data:
